### PR TITLE
Adjust memcache module path for multisite structure.

### PR DESCRIPTION
**Pull request by tkiseleva**
We have multisite, where contrib modules stored in sites/<site name> directory, in this case, memcache settings not applied.
Added one more path to check if the memcache module exists.

### CODE REVIEW

**Comment by danepowell** [comment]
Are you able to move the memcache module to `docroot/modules/contrib`? While storing modules in the `sites` directory might still technically be supported in Drupal 8 (it was more common in earlier versions), I think you're going to run into a lot of edge cases like this because most tooling assumes modules are at `docroot/modules` or `docroot/modules/contrib`.

**Comment by tkiseleva** [comment]
Previously we had it in contrib, but moved to sites due to some internal reasons of the client.
So we can't move it back for now.

**Comment by danepowell** [comment]
I guess there's an argument that we need this to support Drupal 7, I assume that's why you need it since putting modules in the sites directory would be highly unorthodox (probably wouldn't work at all) in Drupal 9/10.

@janusman could you please review this?

**Comment by janusman** [comment]
The code would now require the Blt environment detector (IIUC) so this code would break if a site didn't also have BLT. So, just for that, as is, the code would need changing.

However, I disagree with accepting this patch. I think the code is supposed to be simple, and a little (or a lot?) opinionated. I think it's OK to not accept this and just mention, in documentation, that the memcache module should exist on drupal/modules/contrib/memcache, but also that If someone needs (for some reason) put the module elsewhere, they can just make a symlink in drupal/modules/contrib/memcache that points to the "real" folder for the memcache module. Or, someone could patch this library after-the-fact within composer to point to whatever folder they need.

**Comment by danepowell** [comment]
Thanks for the input! Agreed that this is not the best approach.

**Pull request closed without merging**
